using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using YtDlpGui.Models;
using YtDlpGui.Tools;

namespace YtDlpGui.Services;

// ==================================================
// キュー追加時に使うダウンロード設定
// （画質・音質・形式など、UIで選択されているもの）
// ==================================================

public class QueueAddOptions
{
    public string Quality { get; init; } = "最高";

    public string AudioQuality { get; init; } = "最高";

    public string Format { get; init; } = "MP4";

    public bool PlaylistFolderEnabled { get; init; } = true;

    public string FileNameTemplate { get; init; } =
        "%(title)s.%(ext)s";
}


// ==================================================
// キュー処理時に使うダウンロード設定
// （保存先や字幕などの、MainViewModel側の設定）
// ==================================================

public class DownloadJobOptions
{
    public string OutputDirectory { get; init; } = "";

    public bool ThumbnailEnabled { get; init; } = true;

    public bool SubtitleEnabled { get; init; } = true;

    public bool AutoGeneratedSubtitleEnabled { get; init; }
}


// ==================================================
// QueueManager
//
// ★ 分割リファクタリング
//
// 以前はMainViewModelに同居していた、
// 「キューへの追加」「キューの処理」「進捗計算」
// 「キャンセル・再試行・削除」を、ここへ集約した。
//
// MainViewModel自身が持っていたStatus/Progress/
// ErrorMessage/IsProcessingQueueといった
// バインド用プロパティはそのままMainViewModel側に残し、
// QueueManagerはコールバック(OnStatusChanged等)を通じて
// それらの更新をMainViewModelへ依頼する形にしている。
// これによりMainView.axaml側のバインディングを
// 一切変更せずに済んでいる。
//
// 挙動は分割前と同一になるよう、元のMainViewModel内の
// 実装をそのまま移設しただけで、ロジック自体は
// 変更していない。
// ==================================================

public class QueueManager
{
    private readonly YtDlpService _ytDlpService;

    private CancellationTokenSource?
        _queueCancellationTokenSource;

    private bool _queueCancellationRequested;

    private bool _isProcessingQueue;


    // ==================================================
    // キュー本体
    //
    // MainViewModel側はこのインスタンスをそのまま
    // 公開する（参照は不変なのでXAMLバインディングに
    // 影響しない）。
    // ==================================================

    public ObservableCollection<DownloadQueueItem>
        DownloadQueue
    {
        get;
    } = new();


    public bool IsProcessingQueue =>
        _isProcessingQueue;


    // ==================================================
    // MainViewModelへの通知用コールバック
    // ==================================================

    public Action<string>? OnStatusChanged;

    public Action<double>? OnProgressChanged;

    public Action<string>? OnErrorChanged;

    public Action<bool>? OnProcessingChanged;


    public QueueManager(
        YtDlpService ytDlpService)
    {
        _ytDlpService =
            ytDlpService
            ?? throw new ArgumentNullException(
                nameof(ytDlpService));
    }


    private void ReportStatus(
        string status)
    {
        OnStatusChanged?.Invoke(
            status);
    }


    private void ReportProgress(
        double progress)
    {
        OnProgressChanged?.Invoke(
            progress);
    }


    private void ReportError(
        string error)
    {
        OnErrorChanged?.Invoke(
            error);
    }


    private void SetProcessing(
        bool value)
    {
        if (_isProcessingQueue == value)
            return;

        _isProcessingQueue = value;

        OnProcessingChanged?.Invoke(
            value);
    }


    // ==================================================
    // キュー追加
    //
    // 通常URLかプレイリストURLかをyt-dlpへ問い合わせて
    // 判定し、それぞれ専用の処理へ振り分ける。
    // （仕様6〜7章：プレイリストは個別のキュー項目へ展開する）
    //
    // 戻り値：単一動画の場合はその動画情報、
    //         プレイリストの場合はnull
    //         （MainViewModel側のVideoInfoプレビュー表示用）
    // ==================================================

    public async Task<VideoInfo?> AddToQueueAsync(
        string url,
        QueueAddOptions options)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return null;
        }


        // ==================================================
        // 重複確認（通常URL用。プレイリストの場合は
        // 展開後に動画単位で個別チェックする）
        // ==================================================

        if (DownloadQueue.Any(
                x =>
                    string.Equals(
                        x.Url,
                        url,
                        StringComparison.OrdinalIgnoreCase)))
        {
            ReportStatus(
                "このURLはすでにキューに追加されています。");

            return null;
        }


        ReportStatus(
            "URLを確認しています...");


        PlaylistInfo? playlistInfo =
            null;


        try
        {
            playlistInfo =
                await _ytDlpService
                    .GetPlaylistInfoAsync(
                        url);
        }
        catch
        {
            // ==================================================
            // プレイリストとしての取得に失敗しても、
            // 通常の動画URLとして処理を継続する。
            // （単体動画URLに対してプレイリスト解析を
            //   行うと失敗するケースがあるため）
            // ==================================================
        }


        bool isPlaylist =
            playlistInfo != null &&
            playlistInfo.Entries.Count > 0;


        VideoInfo? result;


        if (isPlaylist)
        {
            await AddPlaylistToQueueAsync(
                playlistInfo!,
                options);

            result = null;
        }
        else
        {
            result =
                await AddSingleVideoToQueueAsync(
                    url,
                    options);
        }


        return result;
    }


    // ==================================================
    // 通常URLをキューへ追加
    // ==================================================

    private async Task<VideoInfo?>
        AddSingleVideoToQueueAsync(
            string url,
            QueueAddOptions options)
    {
        VideoInfo? info =
            null;


        try
        {
            ReportStatus(
                "動画情報を取得中...");


            info =
                await _ytDlpService
                    .GetVideoInfoAsync(
                        url);
        }
        catch
        {
            // 情報取得に失敗しても
            // URL自体はキューへ追加する
        }


        var item =
            new DownloadQueueItem
            {
                Url =
                    url,

                Title =
                    info?.Title
                    ?? url,

                Channel =
                    info?.Channel
                    ?? "",

                PlaylistTitle =
                    info?.PlaylistTitle
                    ?? "",

                Quality =
                    options.Quality,

                AudioQuality =
                    options.AudioQuality,

                Format =
                    options.Format,

                PlaylistFolderEnabled =
                    options.PlaylistFolderEnabled,

                FileNameTemplate =
                    options.FileNameTemplate,

                Status =
                    "待機中",

                Progress =
                    0
            };


        DownloadQueue.Add(
            item);


        ReportStatus(
            "キューに追加しました。");


        return info;
    }


    // ==================================================
    // プレイリストURLを個別のキュー項目へ展開
    //
    // 仕様8章：各動画には同じダウンロード設定
    // （画質・音質・形式など）を適用する。
    // ==================================================

    private async Task AddPlaylistToQueueAsync(
        PlaylistInfo playlistInfo,
        QueueAddOptions options)
    {
        int addedCount = 0;

        int skippedCount = 0;


        foreach (PlaylistEntry entry
            in playlistInfo.Entries)
        {
            if (string.IsNullOrWhiteSpace(
                    entry.Url))
            {
                continue;
            }


            // ==================================================
            // 既にキューにある動画は重複追加しない
            // ==================================================

            if (DownloadQueue.Any(
                    x =>
                        string.Equals(
                            x.Url,
                            entry.Url,
                            StringComparison.OrdinalIgnoreCase)))
            {
                skippedCount++;

                continue;
            }


            var item =
                new DownloadQueueItem
                {
                    Url =
                        entry.Url,

                    Title =
                        string.IsNullOrWhiteSpace(
                            entry.Title)
                            ? entry.Url
                            : entry.Title,

                    Channel =
                        "",

                    PlaylistTitle =
                        playlistInfo.Title,

                    Quality =
                        options.Quality,

                    AudioQuality =
                        options.AudioQuality,

                    Format =
                        options.Format,

                    PlaylistFolderEnabled =
                        options.PlaylistFolderEnabled,

                    FileNameTemplate =
                        options.FileNameTemplate,

                    Status =
                        "待機中",

                    Progress =
                        0
                };


            DownloadQueue.Add(
                item);

            addedCount++;


            // ==================================================
            // 大量のプレイリストでもUIが固まらないよう
            // 1件ごとにUIスレッドへ制御を返す
            // ==================================================

            await Task.Yield();
        }


        if (addedCount == 0)
        {
            ReportStatus(
                skippedCount > 0
                    ? "プレイリスト内の動画はすべて追加済みです。"
                    : "プレイリストから追加できる動画がありませんでした。");
        }
        else
        {
            string playlistLabel =
                string.IsNullOrWhiteSpace(
                    playlistInfo.Title)
                    ? "プレイリスト"
                    : playlistInfo.Title;


            ReportStatus(
                skippedCount > 0
                    ? $"{playlistLabel} から {addedCount}件を追加しました" +
                      $"（{skippedCount}件は追加済みのためスキップ）。"
                    : $"{playlistLabel} から {addedCount}件をキューに追加しました。");
        }
    }


    // ==================================================
    // キュー開始
    // ==================================================

    public async Task StartQueueAsync(
        DownloadJobOptions jobOptions)
    {
        if (_isProcessingQueue)
        {
            return;
        }


        if (DownloadQueue.Count == 0)
        {
            ReportStatus(
                "キューが空です。");

            return;
        }


        if (string.IsNullOrWhiteSpace(
                jobOptions.OutputDirectory))
        {
            ReportStatus(
                "保存先を指定してください。");

            return;
        }


        SetProcessing(
            true);


        _queueCancellationRequested =
            false;


        _queueCancellationTokenSource =
            new CancellationTokenSource();


        ReportProgress(
            0);


        ReportError(
            "");


        try
        {
            await ProcessQueueAsync(
                jobOptions,
                _queueCancellationTokenSource.Token);
        }
        catch (OperationCanceledException)
        {
            _queueCancellationRequested =
                true;
        }
        catch (Exception ex)
        {
            ReportError(
                ex.Message);


            ReportStatus(
                $"キュー処理エラー: {ex.Message}");
        }
        finally
        {
            _queueCancellationTokenSource
                ?.Dispose();


            _queueCancellationTokenSource =
                null;


            SetProcessing(
                false);


            if (_queueCancellationRequested)
            {
                ReportStatus(
                    "キューをキャンセルしました。");
            }
            else if (
                DownloadQueue.Count > 0 &&
                DownloadQueue.All(
                    x =>
                        x.Status == "完了" ||
                        x.Status == "エラー"))
            {
                ReportStatus(
                    "キューの処理が完了しました。");
            }
        }
    }


    // ==================================================
    // キュー処理
    // ==================================================

    private async Task ProcessQueueAsync(
        DownloadJobOptions jobOptions,
        CancellationToken cancellationToken)
    {
        int total =
            DownloadQueue.Count;


        if (total <= 0)
        {
            ReportProgress(
                0);

            return;
        }


        for (int i = 0;
             i < total;
             i++)
        {
            // ==================================================
            // キャンセル確認
            // ==================================================

            if (_queueCancellationRequested ||
                cancellationToken.IsCancellationRequested)
            {
                break;
            }


            // ==================================================
            // ★ 重要
            //
            // キュー処理中にコレクションが変更される可能性を
            // 考慮し、現在の件数を必ず確認する。
            // ==================================================

            if (i < 0 ||
                i >= DownloadQueue.Count)
            {
                break;
            }


            DownloadQueueItem item =
                DownloadQueue[i];


            // ==================================================
            // 完了済みはスキップ
            // ==================================================

            if (item.Status == "完了")
            {
                UpdateOverallProgress(
                    i,
                    total);

                continue;
            }


            // ==================================================
            // キュー項目開始
            // ==================================================

            item.Status =
                "ダウンロード中";


            item.ErrorMessage =
                "";


            item.Progress =
                0;


            ReportStatus(
                $"ダウンロード中... {i + 1}/{total}");


            try
            {
                cancellationToken
                    .ThrowIfCancellationRequested();


                // ==================================================
                // 個別進捗
                // ==================================================

                var itemProgress =
                    new Progress<double>(
                        value =>
                        {
                            // 項目自身の進捗だけ更新
                            item.Progress =
                                Math.Clamp(
                                    value,
                                    0,
                                    100);


                            // 全体進捗を安全に更新
                            UpdateOverallProgress(
                                i,
                                total);
                        });


                // ==================================================
                // ダウンロード
                // ==================================================

                await _ytDlpService
                    .DownloadAsync(
                        item.Url,
                        item.Quality,
                        item.AudioQuality,
                        item.Format,
                        jobOptions.OutputDirectory,
                        jobOptions.ThumbnailEnabled,
                        jobOptions.SubtitleEnabled,
                        jobOptions.AutoGeneratedSubtitleEnabled,
                        itemProgress);


                cancellationToken
                    .ThrowIfCancellationRequested();


                // ==================================================
                // 成功
                // ==================================================

                item.Progress =
                    100;


                item.Status =
                    "完了";


                item.ErrorMessage =
                    "";


                UpdateOverallProgress(
                    i,
                    total);


                ReportStatus(
                    $"完了: {i + 1}/{total}");
            }
            catch (OperationCanceledException)
            {
                // ==================================================
                // キュー全体のキャンセル
                // ==================================================

                item.Status =
                    "キャンセル";


                ReportStatus(
                    "キャンセルしています...");


                break;
            }
            catch (Exception ex)
            {
                // ==================================================
                // 1件の失敗ではキューを停止しない
                // ==================================================

                item.Status =
                    "エラー";


                item.ErrorMessage =
                    ex.Message;


                item.Progress =
                    0;


                UpdateOverallProgress(
                    i,
                    total);


                ReportStatus(
                    $"エラー: {i + 1}/{total}");


                // 次の動画へ進む
                continue;
            }
        }
    }


    // ==================================================
    // 全体進捗更新
    // ==================================================

    private void UpdateOverallProgress(
        int currentIndex,
        int total)
    {
        if (total <= 0)
        {
            ReportProgress(
                0);

            return;
        }


        // ==================================================
        // ★ IndexOutOfRangeException対策
        //
        // currentIndexを直接コレクションのIndexとして
        // 信用しない。
        // ==================================================

        int actualCount =
            DownloadQueue.Count;


        if (actualCount <= 0)
        {
            ReportProgress(
                0);

            return;
        }


        int safeTotal =
            Math.Min(
                Math.Max(total, 1),
                actualCount);


        int safeCurrentIndex =
            Math.Clamp(
                currentIndex,
                0,
                safeTotal - 1);


        // ==================================================
        // 完了済み件数
        //
        // 現在ダウンロード中の項目はここには含めない。
        // ==================================================

        int completedCount = 0;


        for (int index = 0;
             index < safeTotal;
             index++)
        {
            if (DownloadQueue[index].Status ==
                "完了")
            {
                completedCount++;
            }
        }


        // ==================================================
        // 現在の動画
        // ==================================================

        double currentProgress = 0;


        if (safeCurrentIndex <
            DownloadQueue.Count)
        {
            currentProgress =
                Math.Clamp(
                    DownloadQueue[
                        safeCurrentIndex]
                        .Progress,
                    0,
                    100) /
                100.0;
        }


        // ==================================================
        // 全体進捗
        // ==================================================

        double overall =
            (
                completedCount +
                currentProgress
            )
            /
            safeTotal
            *
            100.0;


        ReportProgress(
            Math.Clamp(
                overall,
                0,
                100));
    }


    // ==================================================
    // 現在の全体進捗を再計算
    //
    // （キュー処理中ではないタイミング、
    //   再試行・削除の直後などに使う）
    // ==================================================

    public double CalculateCurrentOverallProgress()
    {
        int total =
            DownloadQueue.Count;


        if (total <= 0)
            return 0;


        double sum =
            DownloadQueue.Sum(
                item =>
                    Math.Clamp(
                        item.Progress,
                        0,
                        100));


        return Math.Clamp(
            sum / total,
            0,
            100);
    }


    // ==================================================
    // キャンセル
    // ==================================================

    public void CancelQueue()
    {
        if (!_isProcessingQueue)
        {
            return;
        }


        _queueCancellationRequested =
            true;


        try
        {
            _queueCancellationTokenSource
                ?.Cancel();
        }
        catch
        {
            // 無視
        }


        try
        {
            _ytDlpService
                .CancelDownload();
        }
        catch
        {
            // 無視
        }


        ReportStatus(
            "キャンセルしています...");
    }


    // ==================================================
    // 再試行
    // ==================================================

    public void RetryQueueItem(
        DownloadQueueItem? item)
    {
        if (_isProcessingQueue)
        {
            return;
        }


        if (item == null)
        {
            return;
        }


        if (!item.HasError)
        {
            return;
        }


        item.Status =
            "待機中";


        item.ErrorMessage =
            "";


        item.Progress =
            0;


        ReportStatus(
            "再試行待ちにしました。");


        ReportProgress(
            CalculateCurrentOverallProgress());
    }


    // ==================================================
    // キュー全削除
    // ==================================================

    public void ClearQueue()
    {
        if (_isProcessingQueue)
        {
            return;
        }


        DownloadQueue.Clear();


        ReportProgress(
            0);


        ReportError(
            "");


        ReportStatus(
            "キューをクリアしました。");
    }


    // ==================================================
    // キュー項目削除
    // ==================================================

    public void RemoveQueueItem(
        DownloadQueueItem? item)
    {
        if (_isProcessingQueue)
        {
            return;
        }


        if (item == null)
        {
            return;
        }


        DownloadQueue.Remove(
            item);


        ReportProgress(
            CalculateCurrentOverallProgress());


        ReportStatus(
            "キューから削除しました。");
    }
}
