using Avalonia;
using Avalonia.Controls;
using Avalonia.Platform.Storage;
using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Windows.Input;
using YtDlpGui.Commands;
using YtDlpGui.Models;
using YtDlpGui.Services;
using YtDlpGui.Tools;

namespace YtDlpGui.ViewModels;

public class SettingsViewModel : INotifyPropertyChanged
{
    // ==================================================
    // フィールド
    // ==================================================

    private readonly ToolManager _toolManager;

    private readonly ToolDownloader _toolDownloader;

    private readonly INavigationService _navigationService;


    // ==================================================
    // 呼び出し元のMainViewModel
    //
    // 「戻る」の際にnew MainViewModel()せず、
    // このインスタンスへ設定を再反映するだけにする。
    // これによりダウンロードキューが消えなくなる。
    // ==================================================

    private readonly MainViewModel _owner;

    private AppSettings _settings;

    private string _selectedQuality = "最高";

    private string _selectedAudioQuality = "最高";

    private string _selectedFormat = "MP4";

    private string _outputDirectory = "";

    private bool _thumbnailEnabled = true;

    private bool _subtitleEnabled = true;

    private bool _autoGeneratedSubtitleEnabled = false;

    private bool _playlistFolderEnabled = true;

    private string _fileNameTemplate =
        "%(title)s.%(ext)s";

    private string _ytDlpVersion =
        "確認中...";

    private string _ffmpegVersion =
        "確認中...";

    private string _ffprobeVersion =
        "確認中...";

    private string _denoVersion =
        "確認中...";

    private string _statusText =
        "設定を読み込んでいます...";

    private double _progress;

    private bool _isBusy;


    // ==================================================
    // コンストラクター
    // ==================================================

    public SettingsViewModel(
        ToolManager toolManager,
        INavigationService navigationService,
        MainViewModel owner)
    {
        // ==================================================
        // ★ 重要
        //
        // 以前はここで独自に new ToolManager() していたため、
        // MainViewModel側のToolManagerとは別インスタンスに
        // なってしまい、ツールの状態把握が2系統に
        // 分裂していた。呼び出し元から同じインスタンスを
        // 受け取ることで一本化する。
        // ==================================================

        _toolManager =
            toolManager
            ?? throw new ArgumentNullException(
                nameof(toolManager));

        _navigationService =
            navigationService
            ?? throw new ArgumentNullException(
                nameof(navigationService));

        _owner =
            owner
            ?? throw new ArgumentNullException(
                nameof(owner));

        _toolDownloader =
            new ToolDownloader(
                _toolManager);


        QualityOptions =
            new ObservableCollection<string>
            {
                "最高",
                "2160p (4K)",
                "1440p (2K)",
                "1080p",
                "720p",
                "480p",
                "360p"
            };


        AudioQualityOptions =
            new ObservableCollection<string>
            {
                "最高",
                "320kbps",
                "256kbps",
                "192kbps",
                "128kbps"
            };


        FormatOptions =
            new ObservableCollection<string>
            {
                "MP4",
                "MKV",
                "WebM",
                "MP3",
                "M4A",
                "FLAC",
                "WAV"
            };


        SaveCommand =
            new RelayCommand(
                _ => Save(),
                _ => !IsBusy);


        ResetCommand =
            new RelayCommand(
                _ => Reset(),
                _ => !IsBusy);


        BrowseCommand =
            new RelayCommand(
                _ => Browse(),
                _ => !IsBusy);


        UpdateYtDlpCommand =
            new RelayCommand(
                _ => UpdateYtDlp(),
                _ => !IsBusy);


        UpdateFfmpegCommand =
            new RelayCommand(
                _ => UpdateFfmpeg(),
                _ => !IsBusy);


        UpdateDenoCommand =
            new RelayCommand(
                _ => UpdateDeno(),
                _ => !IsBusy);


        RefreshToolsCommand =
            new RelayCommand(
                _ => RefreshTools(),
                _ => !IsBusy);


        BackCommand =
            new RelayCommand(
                _ => Back(),
                _ => !IsBusy);


        _settings =
            AppSettings.CreateDefault();


        LoadSettings();
    }


    // ==================================================
    // Options
    // ==================================================

    public ObservableCollection<string>
        QualityOptions
    {
        get;
    }


    public ObservableCollection<string>
        AudioQualityOptions
    {
        get;
    }


    public ObservableCollection<string>
        FormatOptions
    {
        get;
    }


    // ==================================================
    // 画質
    // ==================================================

    public string SelectedQuality
    {
        get => _selectedQuality;

        set
        {
            if (_selectedQuality == value)
                return;

            _selectedQuality = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 音質
    // ==================================================

    public string SelectedAudioQuality
    {
        get => _selectedAudioQuality;

        set
        {
            if (_selectedAudioQuality == value)
                return;

            _selectedAudioQuality = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 形式
    // ==================================================

    public string SelectedFormat
    {
        get => _selectedFormat;

        set
        {
            if (_selectedFormat == value)
                return;

            _selectedFormat = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 保存先
    // ==================================================

    public string OutputDirectory
    {
        get => _outputDirectory;

        set
        {
            if (_outputDirectory == value)
                return;

            _outputDirectory = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // サムネイル
    // ==================================================

    public bool ThumbnailEnabled
    {
        get => _thumbnailEnabled;

        set
        {
            if (_thumbnailEnabled == value)
                return;

            _thumbnailEnabled = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 字幕
    // ==================================================

    public bool SubtitleEnabled
    {
        get => _subtitleEnabled;

        set
        {
            if (_subtitleEnabled == value)
                return;

            _subtitleEnabled = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 自動生成字幕
    // ==================================================

    public bool AutoGeneratedSubtitleEnabled
    {
        get => _autoGeneratedSubtitleEnabled;

        set
        {
            if (_autoGeneratedSubtitleEnabled == value)
                return;

            _autoGeneratedSubtitleEnabled = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // プレイリストフォルダー
    // ==================================================

    public bool PlaylistFolderEnabled
    {
        get => _playlistFolderEnabled;

        set
        {
            if (_playlistFolderEnabled == value)
                return;

            _playlistFolderEnabled = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // ファイル名テンプレート
    // ==================================================

    public string FileNameTemplate
    {
        get => _fileNameTemplate;

        set
        {
            if (_fileNameTemplate == value)
                return;

            _fileNameTemplate = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // yt-dlp
    // ==================================================

    public string YtDlpVersion
    {
        get => _ytDlpVersion;

        private set
        {
            if (_ytDlpVersion == value)
                return;

            _ytDlpVersion = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // FFmpeg
    // ==================================================

    public string FfmpegVersion
    {
        get => _ffmpegVersion;

        private set
        {
            if (_ffmpegVersion == value)
                return;

            _ffmpegVersion = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // FFprobe
    // ==================================================

    public string FfprobeVersion
    {
        get => _ffprobeVersion;

        private set
        {
            if (_ffprobeVersion == value)
                return;

            _ffprobeVersion = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // Deno
    // ==================================================

    public string DenoVersion
    {
        get => _denoVersion;

        private set
        {
            if (_denoVersion == value)
                return;

            _denoVersion = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 更新状態（最新版かどうか）
    //
    // "" ＝ 未インストール、または未確認
    // "(最新です)" / "(更新あり: ...)" / "(確認できませんでした)"
    // のような短い文字列を保持し、バージョン表示の隣に出す。
    // ==================================================

    private string _ytDlpUpdateStatus = "";

    public string YtDlpUpdateStatus
    {
        get => _ytDlpUpdateStatus;

        private set
        {
            if (_ytDlpUpdateStatus == value)
                return;

            _ytDlpUpdateStatus = value;

            OnPropertyChanged();
        }
    }


    private string _ffmpegUpdateStatus = "";

    public string FfmpegUpdateStatus
    {
        get => _ffmpegUpdateStatus;

        private set
        {
            if (_ffmpegUpdateStatus == value)
                return;

            _ffmpegUpdateStatus = value;

            OnPropertyChanged();
        }
    }


    private string _denoUpdateStatus = "";

    public string DenoUpdateStatus
    {
        get => _denoUpdateStatus;

        private set
        {
            if (_denoUpdateStatus == value)
                return;

            _denoUpdateStatus = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // ステータス
    // ==================================================

    public string StatusText
    {
        get => _statusText;

        private set
        {
            if (_statusText == value)
                return;

            _statusText = value;

            OnPropertyChanged();
        }
    }


    // ==================================================
    // 進捗
    // ==================================================

    public double Progress
    {
        get => _progress;

        private set
        {
            double newValue =
                Math.Clamp(
                    value,
                    0,
                    100);


            if (Math.Abs(
                    _progress - newValue) < 0.001)
            {
                return;
            }


            _progress =
                newValue;


            OnPropertyChanged();

            OnPropertyChanged(
                nameof(ProgressText));
        }
    }


    public string ProgressText =>
        $"{Progress:0}%";


    // ==================================================
    // Busy
    // ==================================================

    public bool IsBusy
    {
        get => _isBusy;

        private set
        {
            if (_isBusy == value)
                return;

            _isBusy = value;

            OnPropertyChanged();

            RaiseCommandStates();
        }
    }


    // ==================================================
    // Commands
    // ==================================================

    public ICommand SaveCommand
    {
        get;
    }


    public ICommand ResetCommand
    {
        get;
    }


    public ICommand BrowseCommand
    {
        get;
    }


    public ICommand UpdateYtDlpCommand
    {
        get;
    }


    public ICommand UpdateFfmpegCommand
    {
        get;
    }


    public ICommand UpdateDenoCommand
    {
        get;
    }


    public ICommand RefreshToolsCommand
    {
        get;
    }


    public ICommand BackCommand
    {
        get;
    }


    // ==================================================
    // 設定読み込み
    // ==================================================

    private async void LoadSettings()
    {
        try
        {
            IsBusy = true;

            StatusText =
                "設定を読み込んでいます...";


            _settings =
                await AppSettings.LoadAsync();


            ApplySettingsToViewModel();


            StatusText =
                "設定を読み込みました";


            await RefreshToolsAsync();
        }
        catch (Exception ex)
        {
            StatusText =
                $"設定読み込みエラー: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }


    // ==================================================
    // 設定 → ViewModel
    // ==================================================

    private void ApplySettingsToViewModel()
    {
        SelectedQuality =
            _settings.DefaultQuality;

        SelectedAudioQuality =
            _settings.DefaultAudioQuality;

        SelectedFormat =
            _settings.DefaultFormat;

        OutputDirectory =
            _settings.OutputDirectory;

        ThumbnailEnabled =
            _settings.ThumbnailEnabled;

        SubtitleEnabled =
            _settings.SubtitleEnabled;

        AutoGeneratedSubtitleEnabled =
            _settings.AutoGeneratedSubtitleEnabled;

        PlaylistFolderEnabled =
            _settings.PlaylistFolderEnabled;

        FileNameTemplate =
            _settings.FileNameTemplate;
    }


    // ==================================================
    // ViewModel → 設定
    // ==================================================

    private void ApplyViewModelToSettings()
    {
        _settings.DefaultQuality =
            SelectedQuality;

        _settings.DefaultAudioQuality =
            SelectedAudioQuality;

        _settings.DefaultFormat =
            SelectedFormat;

        _settings.OutputDirectory =
            OutputDirectory;

        _settings.ThumbnailEnabled =
            ThumbnailEnabled;

        _settings.SubtitleEnabled =
            SubtitleEnabled;

        _settings.AutoGeneratedSubtitleEnabled =
            AutoGeneratedSubtitleEnabled;

        _settings.PlaylistFolderEnabled =
            PlaylistFolderEnabled;

        _settings.FileNameTemplate =
            FileNameTemplate;
    }


    // ==================================================
    // 保存
    // ==================================================

    private void Save()
    {
        _ = SaveAsync();
    }


    private async Task SaveAsync()
    {
        try
        {
            IsBusy = true;

            Progress = 0;

            StatusText =
                "設定を保存しています...";


            ApplyViewModelToSettings();


            await _settings.SaveAsync();


            Progress = 100;

            StatusText =
                "設定を保存しました";
        }
        catch (Exception ex)
        {
            StatusText =
                $"設定保存エラー: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }


    // ==================================================
    // 初期化
    // ==================================================

    private void Reset()
    {
        try
        {
            _settings =
                AppSettings.CreateDefault();


            ApplySettingsToViewModel();


            StatusText =
                "設定を初期値に戻しました";
        }
        catch (Exception ex)
        {
            StatusText =
                $"設定初期化エラー: {ex.Message}";
        }
    }


    // ==================================================
    // 保存先参照
    // ==================================================

    private void Browse()
    {
        _ = BrowseAsync();
    }


    private async Task BrowseAsync()
    {
        try
        {
            var desktop =
                Application.Current?
                    .ApplicationLifetime
                    as Avalonia.Controls
                        .ApplicationLifetimes
                        .IClassicDesktopStyleApplicationLifetime;


            var window =
                desktop?.MainWindow;


            if (window == null)
            {
                StatusText =
                    "ウィンドウを取得できませんでした";

                return;
            }


            var result =
                await window.StorageProvider
                    .OpenFolderPickerAsync(
                        new FolderPickerOpenOptions
                        {
                            Title =
                                "デフォルト保存先を選択",

                            AllowMultiple =
                                false
                        });


            if (result.Count == 0)
                return;


            string? path =
                result[0]
                    .TryGetLocalPath();


            if (!string.IsNullOrWhiteSpace(path))
            {
                OutputDirectory =
                    path;


                StatusText =
                    "保存先を変更しました";
            }
        }
        catch (Exception ex)
        {
            StatusText =
                $"保存先選択エラー: {ex.Message}";
        }
    }


    // ==================================================
    // yt-dlp更新
    // ==================================================

    private void UpdateYtDlp()
    {
        _ = UpdateYtDlpAsync();
    }


    private async Task UpdateYtDlpAsync()
    {
        try
        {
            IsBusy = true;

            Progress = 0;

            StatusText =
                "yt-dlpを更新しています...";


            var progress =
                new Progress<double>(
                    value =>
                    {
                        Progress = value;

                        StatusText =
                            $"yt-dlpを更新しています... " +
                            $"{value:0}%";
                    });


            await _toolDownloader
                .DownloadYtDlpAsync(
                    progress);


            Progress = 100;

            StatusText =
                "yt-dlpの更新が完了しました";


            await RefreshToolsAsync();
        }
        catch (Exception ex)
        {
            StatusText =
                $"yt-dlp更新エラー: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }


    // ==================================================
    // FFmpeg更新
    // ==================================================

    private void UpdateFfmpeg()
    {
        _ = UpdateFfmpegAsync();
    }


    private async Task UpdateFfmpegAsync()
    {
        try
        {
            IsBusy = true;

            Progress = 0;

            StatusText =
                "FFmpegを更新しています...";


            var progress =
                new Progress<double>(
                    value =>
                    {
                        Progress = value;

                        StatusText =
                            $"FFmpegを更新しています... " +
                            $"{value:0}%";
                    });


            await _toolDownloader
                .DownloadFfmpegAsync(
                    progress);


            Progress = 100;

            StatusText =
                "FFmpeg / FFprobeの更新が完了しました";


            await RefreshToolsAsync();
        }
        catch (Exception ex)
        {
            StatusText =
                $"FFmpeg更新エラー: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }


    // ==================================================
    // Deno更新
    // ==================================================

    private void UpdateDeno()
    {
        _ = UpdateDenoAsync();
    }


    private async Task UpdateDenoAsync()
    {
        try
        {
            IsBusy = true;

            Progress = 0;

            StatusText =
                "Denoを更新しています...";


            var progress =
                new Progress<double>(
                    value =>
                    {
                        Progress = value;

                        StatusText =
                            $"Denoを更新しています... " +
                            $"{value:0}%";
                    });


            await _toolDownloader
                .DownloadDenoAsync(
                    progress);


            Progress = 100;

            StatusText =
                "Denoの更新が完了しました";


            await RefreshToolsAsync();
        }
        catch (Exception ex)
        {
            StatusText =
                $"Deno更新エラー: {ex.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }


    // ==================================================
    // ツール確認
    // ==================================================

    private void RefreshTools()
    {
        _ = RefreshToolsAsync();
    }


    private async Task RefreshToolsAsync()
    {
        try
        {
            StatusText =
                "ツールのバージョンを確認しています...";


            YtDlpVersion =
                await _toolManager
                    .GetYtDlpVersionAsync();


            FfmpegVersion =
                await _toolManager
                    .GetFfmpegVersionAsync();


            FfprobeVersion =
                await _toolManager
                    .GetFfprobeVersionAsync();


            DenoVersion =
                await _toolManager
                    .GetDenoVersionAsync();


            StatusText =
                "ツールの確認が完了しました";
        }
        catch (Exception ex)
        {
            StatusText =
                $"ツール確認エラー: {ex.Message}";
        }


        // ==================================================
        // 最新版かどうかの確認
        //
        // ネットワークエラー等で失敗しても、上の
        // バージョン表示自体には影響させない
        // （それぞれ個別にtry/catchする）
        // ==================================================

        await RefreshUpdateStatusAsync();
    }


    // ==================================================
    // 最新版確認
    // ==================================================

    private async Task RefreshUpdateStatusAsync()
    {
        YtDlpUpdateStatus =
            "(確認中...)";

        FfmpegUpdateStatus =
            "(確認中...)";

        DenoUpdateStatus =
            "(確認中...)";


        Task ytDlpTask =
            CheckYtDlpUpdateStatusAsync();

        Task ffmpegTask =
            CheckFfmpegUpdateStatusAsync();

        Task denoTask =
            CheckDenoUpdateStatusAsync();


        await Task.WhenAll(
            ytDlpTask,
            ffmpegTask,
            denoTask);
    }


    private async Task CheckYtDlpUpdateStatusAsync()
    {
        try
        {
            if (!_toolManager.IsYtDlpInstalled)
            {
                YtDlpUpdateStatus =
                    "";

                return;
            }


            string? latest =
                await _toolDownloader
                    .GetLatestYtDlpVersionAsync();


            if (string.IsNullOrWhiteSpace(latest))
            {
                YtDlpUpdateStatus =
                    "(最新版を確認できませんでした)";

                return;
            }


            YtDlpUpdateStatus =
                string.Equals(
                    YtDlpVersion?.Trim(),
                    latest.Trim(),
                    StringComparison.OrdinalIgnoreCase)
                    ? "(最新です)"
                    : $"(更新あり: {latest})";
        }
        catch
        {
            YtDlpUpdateStatus =
                "(最新版を確認できませんでした)";
        }
    }


    private async Task CheckDenoUpdateStatusAsync()
    {
        try
        {
            if (!_toolManager.IsDenoInstalled)
            {
                DenoUpdateStatus =
                    "";

                return;
            }


            string? latest =
                await _toolDownloader
                    .GetLatestDenoVersionAsync();


            if (string.IsNullOrWhiteSpace(latest))
            {
                DenoUpdateStatus =
                    "(最新版を確認できませんでした)";

                return;
            }


            string installed =
                ExtractVersionNumber(
                    DenoVersion);


            DenoUpdateStatus =
                string.Equals(
                    installed,
                    latest.Trim(),
                    StringComparison.OrdinalIgnoreCase)
                    ? "(最新です)"
                    : $"(更新あり: {latest})";
        }
        catch
        {
            DenoUpdateStatus =
                "(最新版を確認できませんでした)";
        }
    }


    // ==================================================
    // "deno 2.1.4 (release, ...)" のような文字列から
    // "2.1.4" だけを抜き出す
    // ==================================================

    private static string ExtractVersionNumber(
        string? versionOutput)
    {
        var match =
            System.Text.RegularExpressions.Regex
                .Match(
                    versionOutput ?? "",
                    @"\d+\.\d+(\.\d+)?");


        return match.Success
            ? match.Value
            : (versionOutput ?? "");
    }


    private async Task CheckFfmpegUpdateStatusAsync()
    {
        try
        {
            if (!_toolManager.IsFfmpegInstalled)
            {
                FfmpegUpdateStatus =
                    "";

                return;
            }


            DateTimeOffset? installedAt =
                await _toolDownloader
                    .GetFfmpegInstalledAtAsync();


            if (installedAt == null)
            {
                // ==================================================
                // この機能を導入する前にインストールされた
                // FFmpegには記録が無いため、判定できない。
                // 一度「更新」すれば以降は判定できるようになる。
                // ==================================================

                FfmpegUpdateStatus =
                    "(導入日時が未記録のため確認できません。" +
                    "一度更新すると以降は確認できます)";

                return;
            }


            DateTimeOffset? latestUpdatedAt =
                await _toolDownloader
                    .GetLatestFfmpegAssetUpdatedAtAsync();


            if (latestUpdatedAt == null)
            {
                FfmpegUpdateStatus =
                    "(最新版を確認できませんでした)";

                return;
            }


            // ==================================================
            // 数分程度の誤差は許容する
            // （ダウンロード完了とGitHub側の更新日時の
            //   タイミングのずれを吸収するため）
            // ==================================================

            FfmpegUpdateStatus =
                latestUpdatedAt.Value >
                installedAt.Value.AddMinutes(5)
                    ? $"(更新あり: " +
                      $"{latestUpdatedAt.Value.ToLocalTime():yyyy/MM/dd} 公開)"
                    : "(最新です)";
        }
        catch
        {
            FfmpegUpdateStatus =
                "(最新版を確認できませんでした)";
        }
    }


    // ==================================================
    // 戻る
    // ==================================================

    private void Back()
    {
        if (IsBusy)
            return;


        // ==================================================
        // ★ 重要
        //
        // 以前はここで new MainViewModel(_toolManager) して
        // いたため、設定画面を開いている間に溜まっていた
        // ダウンロードキューが毎回消えてしまっていた。
        //
        // 保存済みの設定（AppSettings.SaveAsyncで書き込み済み）を
        // 既存のMainViewModelへ再読込させるだけにすることで、
        // キューを保持したまま設定だけを反映する。
        // ==================================================

        _ = _owner.ReloadSettingsAsync();


        _navigationService
            .ShowMain(
                _owner);
    }


    // ==================================================
    // コマンド状態更新
    // ==================================================

    private void RaiseCommandStates()
    {
        if (SaveCommand
            is RelayCommand save)
        {
            save.RaiseCanExecuteChanged();
        }


        if (ResetCommand
            is RelayCommand reset)
        {
            reset.RaiseCanExecuteChanged();
        }


        if (BrowseCommand
            is RelayCommand browse)
        {
            browse.RaiseCanExecuteChanged();
        }


        if (UpdateYtDlpCommand
            is RelayCommand ytdlp)
        {
            ytdlp.RaiseCanExecuteChanged();
        }


        if (UpdateFfmpegCommand
            is RelayCommand ffmpeg)
        {
            ffmpeg.RaiseCanExecuteChanged();
        }


        if (UpdateDenoCommand
            is RelayCommand deno)
        {
            deno.RaiseCanExecuteChanged();
        }


        if (RefreshToolsCommand
            is RelayCommand refresh)
        {
            refresh.RaiseCanExecuteChanged();
        }


        if (BackCommand
            is RelayCommand back)
        {
            back.RaiseCanExecuteChanged();
        }
    }


    // ==================================================
    // PropertyChanged
    // ==================================================

    public event PropertyChangedEventHandler?
        PropertyChanged;


    protected void OnPropertyChanged(
        [CallerMemberName]
        string? propertyName = null)
    {
        PropertyChanged?.Invoke(
            this,
            new PropertyChangedEventArgs(
                propertyName));
    }
}