using System;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;

namespace YtDlpGui.Models;

public class AppSettings
{
    // ==================================================
    // 設定項目
    // ==================================================

    public string DefaultQuality { get; set; } = "最高";

    public string DefaultAudioQuality { get; set; } = "最高";

    public string DefaultFormat { get; set; } = "MP4";

    public string OutputDirectory { get; set; } = "";

    public bool ThumbnailEnabled { get; set; } = true;

    public bool SubtitleEnabled { get; set; } = true;

    public bool AutoGeneratedSubtitleEnabled { get; set; } = false;

    public bool PlaylistFolderEnabled { get; set; } = true;

    public string FileNameTemplate { get; set; } =
        "%(title)s.%(ext)s";


    // ==================================================
    // 設定ファイルパス
    // ==================================================

    private static string SettingsDirectory
    {
        get
        {
            string appData =
                Environment.GetFolderPath(
                    Environment.SpecialFolder.ApplicationData);

            return Path.Combine(
                appData,
                "YtDlpGui");
        }
    }


    private static string SettingsFilePath
    {
        get
        {
            return Path.Combine(
                SettingsDirectory,
                "settings.json");
        }
    }


    // ==================================================
    // デフォルト設定
    // ==================================================

    public static AppSettings CreateDefault()
    {
        return new AppSettings
        {
            DefaultQuality = "最高",

            DefaultAudioQuality = "最高",

            DefaultFormat = "MP4",

            OutputDirectory = "",

            ThumbnailEnabled = true,

            SubtitleEnabled = true,

            AutoGeneratedSubtitleEnabled = false,

            PlaylistFolderEnabled = true,

            FileNameTemplate =
                "%(title)s.%(ext)s"
        };
    }


    // ==================================================
    // 読み込み
    // ==================================================

    public static async Task<AppSettings> LoadAsync()
    {
        try
        {
            if (!File.Exists(SettingsFilePath))
            {
                return CreateDefault();
            }


            string json =
                await File.ReadAllTextAsync(
                    SettingsFilePath);


            if (string.IsNullOrWhiteSpace(json))
            {
                return CreateDefault();
            }


            var settings =
                JsonSerializer.Deserialize<AppSettings>(
                    json,
                    new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });


            return settings
                ?? CreateDefault();
        }
        catch
        {
            // 設定ファイルが壊れていても
            // アプリ自体は起動できるようにする
            return CreateDefault();
        }
    }


    // ==================================================
    // 保存
    // ==================================================

    public async Task SaveAsync()
    {
        Directory.CreateDirectory(
            SettingsDirectory);


        var options =
            new JsonSerializerOptions
            {
                WriteIndented = true
            };


        string json =
            JsonSerializer.Serialize(
                this,
                options);


        await File.WriteAllTextAsync(
            SettingsFilePath,
            json);
    }
}